let funds = [
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Sharing with hope that anyone can offer a hand up out of this hole we are in. I craft and sew to make money from home while I care for my kids, disabled parents and incarcerated husband healing from Covid. Trying to survive. Thank you for retweeting! 💖🙌<a href=\"https://t.co/1hlvTPdsvG\">https://t.co/1hlvTPdsvG</a></p>&mdash; Nikki Rodriguez (@NikkiRo23890574) <a href=\"https://twitter.com/NikkiRo23890574/status/1348147245498171392?ref_src=twsrc%5Etfw\">January 10, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">My grandfather who is dying of cancer is still without money for for his burial. All he wants is to have some time with his family and be buried in our ancestral home in Mississippi. Our black family and many others are in need this <a href=\"https://twitter.com/hashtag/MLKDay?src=hash&amp;ref_src=twsrc%5Etfw\">#MLKDay</a>. Please donate! <a href=\"https://t.co/hvc7kzOwYO\">https://t.co/hvc7kzOwYO</a></p>&mdash; Asha (@ultrafem) <a href=\"https://twitter.com/ultrafem/status/1351244480133922816?ref_src=twsrc%5Etfw\">January 18, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Anything helps guys even just a rt I haven’t reached my goal I’m far from it ☹️ <a href=\"https://t.co/B4lcE6rKju\">https://t.co/B4lcE6rKju</a></p>&mdash; HTX 🎰 (@htx777) <a href=\"https://twitter.com/htx777/status/1351030380023971841?ref_src=twsrc%5Etfw\">January 18, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">⚠️tw/ mentions of abuse &amp; homeless. <br>consider donating to keep a young black girl safe &amp; stable. Please send to <br>$lilnicbee (pāypal and cåshapp)<a href=\"https://twitter.com/CoCoapuffz?ref_src=twsrc%5Etfw\">@cocoapuffz</a> (venmo)<br>even the smallest counts<br>this will help w/ living necessities, thank you. 🙏🏽⚠️ <a href=\"https://t.co/QMHvyeRn0y\">pic.twitter.com/QMHvyeRn0y</a></p>&mdash; 🦋 (@lilnicbee) <a href=\"https://twitter.com/lilnicbee/status/1350967132117475329?ref_src=twsrc%5Etfw\">January 18, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Thanks to all of your support, I have created a GoFundMe to raise money for housing. If y&#39;all could share and boost this, it would mean the world to me.<br><br>Help Mariah and Niko secure stable housing. Click to Donate <a href=\"https://t.co/MYryWGGG27\">https://t.co/MYryWGGG27</a></p>&mdash; garden hoe (@MariahGracex3) <a href=\"https://twitter.com/MariahGracex3/status/1348676487621316609?ref_src=twsrc%5Etfw\">January 11, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">DB had to attend their best friends funeral via Facebook live yesterday. we are trapped in a harmful environment because our only other option is to live on the street. i don&#39;t know what to say other than please help us if you can.<a href=\"https://t.co/IqUrycS8fH\">https://t.co/IqUrycS8fH</a></p>&mdash; psuedocoup puzzle (@repulsive_cut) <a href=\"https://twitter.com/repulsive_cut/status/1350870752816410626?ref_src=twsrc%5Etfw\">January 17, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Debbie is a black trans women in a dangerous living situation and she’s reaching her breaking point. Please support! <a href=\"https://t.co/1QXMwkhrWL\">https://t.co/1QXMwkhrWL</a></p>&mdash; 7 (@Transattentive) <a href=\"https://twitter.com/Transattentive/status/1349890336680599554?ref_src=twsrc%5Etfw\">January 15, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Struggling Black Trans Woman &amp; model relocating to new city and raising funds for food, toiletries &amp; a hotel. Trying to raise a minimum goal of $1000. Please share ✨<br><br>Cashapp: <a href=\"https://t.co/KFOz5MGVqG\">https://t.co/KFOz5MGVqG</a><br>PayPal: <a href=\"https://t.co/LBBot6RR7Z\">https://t.co/LBBot6RR7Z</a><a href=\"https://twitter.com/hashtag/TransCrowdFund?src=hash&amp;ref_src=twsrc%5Etfw\">#TransCrowdFund</a> <a href=\"https://twitter.com/hashtag/Mutualaid?src=hash&amp;ref_src=twsrc%5Etfw\">#Mutualaid</a> <a href=\"https://t.co/UbeJU0DQKP\">pic.twitter.com/UbeJU0DQKP</a></p>&mdash; Dulcé Bartira⚜️ (@Labelle_dulce) <a href=\"https://twitter.com/Labelle_dulce/status/1348579350833225729?ref_src=twsrc%5Etfw\">January 11, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Please make sure to contribute to these crowdfunded efforts from other Black Trans/Queer folk that haven’t met their goal yet:<a href=\"https://t.co/jxGcH222Aq\">https://t.co/jxGcH222Aq</a></p>&mdash; ᖴᗩT ᔕᑌᑭᖇEᗰᗩᑕIᔕT (@fluffyblkboy) <a href=\"https://twitter.com/fluffyblkboy/status/1350341299472392192?ref_src=twsrc%5Etfw\">January 16, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">BOOST ! <a href=\"https://twitter.com/hashtag/BlackLivesMatter?src=hash&amp;ref_src=twsrc%5Etfw\">#BlackLivesMatter</a> <a href=\"https://twitter.com/hashtag/BlackTwitter?src=hash&amp;ref_src=twsrc%5Etfw\">#BlackTwitter</a> <a href=\"https://twitter.com/hashtag/LGBTQ?src=hash&amp;ref_src=twsrc%5Etfw\">#LGBTQ</a> <a href=\"https://t.co/2lbqTQtr8t\">pic.twitter.com/2lbqTQtr8t</a></p>&mdash; Jade Asha (@JadeAsha1) <a href=\"https://twitter.com/JadeAsha1/status/1348674493758238722?ref_src=twsrc%5Etfw\">January 11, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Hey all I&#39;m part of an org helping trans people at risk relocating to other countries and we would need your help to raise fund for a Jamaican trans woman who recently arrived in France to seek asylum with not much<br>Would also love any sort of signal boost!<a href=\"https://t.co/ZgvVRCDML7\">https://t.co/ZgvVRCDML7</a></p>&mdash; Velvette (@VelvetteRld) <a href=\"https://twitter.com/VelvetteRld/status/1349037319735681025?ref_src=twsrc%5Etfw\">January 12, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Raven is a Black trans parent of a toddler. They need $150 to pay for needed medication. Please hit the tag below with direct aid and s/h/ar-e; anything helps. <a href=\"https://t.co/M0jCRCXHCs\">pic.twitter.com/M0jCRCXHCs</a></p>&mdash; b&amp;slave (@bslave7) <a href=\"https://twitter.com/bslave7/status/1349024796856737802?ref_src=twsrc%5Etfw\">January 12, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">hey y’all! rly going out on a whim here but!! my bf and I could rly use the support so!! plz boost, donate, w/e!! One thing I learned is asking ur community for support so here we are!! ❤️❤️<a href=\"https://t.co/TZjzelkD5T\">https://t.co/TZjzelkD5T</a></p>&mdash; moon boy (@GoddexAres) <a href=\"https://twitter.com/GoddexAres/status/1350221261469843458?ref_src=twsrc%5Etfw\">January 15, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">happy fri! we&#39;re pooling up today for our comrades at the trans disabled care fund, a mutual aid project that sends monthly stipends to Black and Indigenous trans disabled individuals in minnesota. we&#39;re aiming to help them fully fund 10 people for 6 months.<br><br>venmo tia-king-2 ‼️ <a href=\"https://t.co/fe39BbUCi6\">pic.twitter.com/fe39BbUCi6</a></p>&mdash; pocket change pools (@pc_pools) <a href=\"https://twitter.com/pc_pools/status/1350108562744352772?ref_src=twsrc%5Etfw\">January 15, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Amber is a disabled Black trans woman who is trying to stay out of sex work to support herself. Fundraising is exhausting but it&#39;s the main way she can meet her basic needs, so please continue donating whatever you can!! If you see this, pls consider don8ing and b//sting! <a href=\"https://t.co/0DUgGdzKsr\">pic.twitter.com/0DUgGdzKsr</a></p>&mdash; escuichi (@nata_fuego) <a href=\"https://twitter.com/nata_fuego/status/1349489677372428291?ref_src=twsrc%5Etfw\">January 13, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">🏳️‍⚧️ Hey everyone! I’m making this GoFundMe for my top surgery and transition aid. Thank you everyone who can help by either donations or shares 🏳️‍⚧️<a href=\"https://t.co/zCWouBLuWk\">https://t.co/zCWouBLuWk</a></p>&mdash; ☿ (@The_Bakunawa) <a href=\"https://twitter.com/The_Bakunawa/status/1349217587972853760?ref_src=twsrc%5Etfw\">January 13, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">sooooo... i made a gofundme transition fund, bc life sucks but i&#39;d like it to suck marginally less 🙃 fr tho, any donations/shares would be v. much appreciated <a href=\"https://twitter.com/hashtag/trans?src=hash&amp;ref_src=twsrc%5Etfw\">#trans</a> <a href=\"https://twitter.com/hashtag/ftm?src=hash&amp;ref_src=twsrc%5Etfw\">#ftm</a> <a href=\"https://twitter.com/hashtag/idkwhattotagimabitembarrassed?src=hash&amp;ref_src=twsrc%5Etfw\">#idkwhattotagimabitembarrassed</a> 🏳️‍⚧️ <a href=\"https://t.co/Bv0yBhzGGR\">https://t.co/Bv0yBhzGGR</a></p>&mdash; al 🦈 (@al_istairs) <a href=\"https://twitter.com/al_istairs/status/1288260402007203846?ref_src=twsrc%5Etfw\">July 28, 2020</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Hi everyone! Can you please RT and Share my gofundme? Im raising money for my top surgery to finally become happy with who i am and not feel this burden on my shoulders. Thank you!!<a href=\"https://t.co/Djnk3XXet2\">https://t.co/Djnk3XXet2</a> <a href=\"https://twitter.com/hashtag/BlackTransLivesMatter?src=hash&amp;ref_src=twsrc%5Etfw\">#BlackTransLivesMatter</a> <a href=\"https://twitter.com/hashtag/ftm?src=hash&amp;ref_src=twsrc%5Etfw\">#ftm</a> <a href=\"https://twitter.com/hashtag/tpoc?src=hash&amp;ref_src=twsrc%5Etfw\">#tpoc</a> <a href=\"https://twitter.com/hashtag/TransLivesMatter?src=hash&amp;ref_src=twsrc%5Etfw\">#TransLivesMatter</a></p>&mdash; Dani (@dani316am) <a href=\"https://twitter.com/dani316am/status/1275784494595936258?ref_src=twsrc%5Etfw\">June 24, 2020</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">My cousin and I are trying to raise money for her boyfriend to get top surgery. Please read about him and donate if you can. He is such an amazing person and deserves to feel at home in his own body 💕 link in my bio <a href=\"https://twitter.com/hashtag/transman?src=hash&amp;ref_src=twsrc%5Etfw\">#transman</a> <a href=\"https://twitter.com/hashtag/ftm?src=hash&amp;ref_src=twsrc%5Etfw\">#ftm</a> <a href=\"https://twitter.com/hashtag/topsurgery?src=hash&amp;ref_src=twsrc%5Etfw\">#topsurgery</a> <a href=\"https://twitter.com/hashtag/gofundme?src=hash&amp;ref_src=twsrc%5Etfw\">#gofundme</a> <a href=\"https://twitter.com/hashtag/transgender?src=hash&amp;ref_src=twsrc%5Etfw\">#transgender</a> <a href=\"https://twitter.com/hashtag/LGBTQ?src=hash&amp;ref_src=twsrc%5Etfw\">#LGBTQ</a> <a href=\"https://twitter.com/hashtag/lgbt?src=hash&amp;ref_src=twsrc%5Etfw\">#lgbt</a> <a href=\"https://t.co/H9vEJkWDWO\">pic.twitter.com/H9vEJkWDWO</a></p>&mdash; c (@CaseyBumann) <a href=\"https://twitter.com/CaseyBumann/status/1289631769247932417?ref_src=twsrc%5Etfw\">August 1, 2020</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {
        "html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">I’m a disabled Jewish lesbian who" +
            " recently moved out of an abusive home. However, I’m still relying on my abuser for transportation. I need help acquiring a vehicle to put distance between me and my abuser<br><br>Venmo: flowerfemme<br>Cashapp: $flowerlesbian<a href=\"https://t.co/sFFsu9PjyL\">https://t.co/sFFsu9PjyL</a></p>&mdash; miryam 🌸 (@fIowerfemme) <a href=\"https://twitter.com/fIowerfemme/status/1350874621881548802?ref_src=twsrc%5Etfw\">January 17, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"
    },
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">hi if you have money consider donating to Joel&#39;s top surgery! <a href=\"https://t.co/lVT8kx11ng\">https://t.co/lVT8kx11ng</a></p>&mdash; An Amalgamation of Wives (@happysaplings) <a href=\"https://twitter.com/happysaplings/status/1349804609842393090?ref_src=twsrc%5Etfw\">January 14, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">hiii friends! please share!! ya girl has been struggling to pay rent these past few months and lowkey my landlord spooked me over the phone the other day, so if you can donate, i would appreciate it so so much!!! thank you ❤️ <a href=\"https://t.co/HXol7WKTdn\">https://t.co/HXol7WKTdn</a></p>&mdash; cherry sp¡ce (@bebefruta) <a href=\"https://twitter.com/bebefruta/status/1348755951034060805?ref_src=twsrc%5Etfw\">January 11, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Struggling Black Transgender Women in SEVERE need of funds for Hormone prescription + groceries + basic needs <br><br>Goal $300 <br><br>Cashapp $sanaiababy</p>&mdash; C. (@Calzbe) <a href=\"https://twitter.com/Calzbe/status/1350953183355527175?ref_src=twsrc%5Etfw\">January 17, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Hi friends. This semester I&#39;m doing my thesis show and a colleague told me that the min price I&#39;d have to pay is 1,500 dollars that I don&#39;t have, any help is appreciated, if u donate hmu and ill send you a print I guess help idk <a href=\"https://t.co/mp4fRphHtl\">https://t.co/mp4fRphHtl</a></p>&mdash; emo chad (@dtchngfrnds4nps) <a href=\"https://twitter.com/dtchngfrnds4nps/status/1351010708025126917?ref_src=twsrc%5Etfw\">January 18, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"und\" dir=\"ltr\"><a" +
            " href=\"https://t.co/VpzoBkh1HB\">https://t.co/VpzoBkh1HB</a></p>&mdash; #1 heart ♡ (@IDALISREIGNS) <a href=\"https://twitter.com/IDALISREIGNS/status/1348714744463511552?ref_src=twsrc%5Etfw\">January 11, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<div class=\"gfm-embed\"" +
            " data-url=\"https://www.gofundme.com/f/a-public-restroom-for-downtown-harrisonburg/widget/large/\"></div><script defer src=\"https://www.gofundme.com/static/js/embed.js\"></script>\n"},
    {"html": "<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Fundraising for my monthly life" +
            " extending chemo and cancer treatment have missed our goal the past few days with me passing out hoping to hang in there long enough to hit our goal <br>PayPal nffc65@gmail.com <br>Venmo <a href=\"https://twitter.com/Robert?ref_src=twsrc%5Etfw\">@Robert</a>-Gillespie-23 <br>Cashapp 3 <a href=\"https://t.co/zjv7lM7eY1\">pic.twitter.com/zjv7lM7eY1</a></p>&mdash; Cancer Sucks (@nffc65) <a href=\"https://twitter.com/nffc65/status/1349885601135300609?ref_src=twsrc%5Etfw\">January 15, 2021</a></blockquote> <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>"},
    {"html": "<div class=\"gfm-embed\"" +
            " data-url=\"https://www.gofundme.com/f/janessas-cancer-support-fund/widget/large/\"></div><script defer src=\"https://www.gofundme.com/static/js/embed.js\"></script>"},
    {"html": "<div class=\"gfm-embed\" data-url=\"https://www.gofundme.com/f/help-gracee-with-medical-bills/widget/large/\"></div><script defer src=\"https://www.gofundme.com/static/js/embed.js\"></script>"},
    {"html": ""},
    {"html": ""},
    {"html": ""},
    {"html": ""},
    {"html": ""},
    {"html": ""},
    {"html": ""},
    {"html": ""},
    {"html": ""},

];